motion_duration_second: 8.0

observation:
  command:
    ref_motion_phase:      {}
  policy:
    root_ang_vel_b:        {}
    projected_gravity_b:   {}
    joint_pos_multistep:   {}
    joint_vel_multistep:   {}
    prev_actions:          {}

action_scale: 0.25

isaac_joint_names: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_roll_joint', 'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_pitch_joint', 'left_knee_joint', 'right_knee_joint', 'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 'left_elbow_joint', 'right_elbow_joint', 'left_wrist_roll_joint', 'right_wrist_roll_joint', 'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_wrist_yaw_joint']

# this should be a subset of isaac_joint_names, contains all the joints that are controlled by the policy
policy_joint_names: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_roll_joint', 'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_pitch_joint', 'left_knee_joint', 'right_knee_joint', 'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 'left_elbow_joint', 'right_elbow_joint']

joint_kp:
  .*_hip_pitch_joint: 200
  .*_hip_roll_joint: 150
  .*_hip_yaw_joint: 150
  .*_knee_joint: 200
  .*_ankle_pitch_joint: 20
  .*_ankle_roll_joint: 20
  waist_yaw_joint: 150
  waist_roll_joint: 150
  waist_pitch_joint: 150
  .*_shoulder_pitch_joint: 40
  .*_shoulder_roll_joint: 40
  .*_shoulder_yaw_joint: 40
  .*_elbow_joint: 40
  .*_wrist_roll_joint: 4
  .*_wrist_pitch_joint: 4
  .*_wrist_yaw_joint: 4

joint_kd:
  .*_hip_pitch_joint: 6.0
  .*_hip_roll_joint: 6.0
  .*_hip_yaw_joint: 6.0
  .*_knee_joint: 6.0
  .*_ankle_pitch_joint: 1.0
  .*_ankle_roll_joint: 1.0
  waist_yaw_joint: 5.0
  waist_roll_joint: 5.0
  waist_pitch_joint: 5.0
  .*_shoulder_pitch_joint: 2.0
  .*_shoulder_roll_joint: 2.0
  .*_shoulder_yaw_joint: 2.0
  .*_elbow_joint: 2.0
  .*_wrist_roll_joint: 0.5
  .*_wrist_pitch_joint: 0.5
  .*_wrist_yaw_joint: 0.5


default_joint_pos:
  left_hip_pitch_joint: -0.1
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 0.6
  left_ankle_pitch_joint: -0.2
  left_ankle_roll_joint: 0.0
  right_hip_pitch_joint: -0.1
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 0.6
  right_ankle_pitch_joint: -0.2
  right_ankle_roll_joint: 0.0
  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0
  left_shoulder_pitch_joint: 0.0
  left_shoulder_roll_joint: 0.0
  left_shoulder_yaw_joint: 0.0
  left_elbow_joint: 1.0
  left_wrist_roll_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_yaw_joint: 0.0
  right_shoulder_pitch_joint: 0.0
  right_shoulder_roll_joint: 0.0
  right_shoulder_yaw_joint: 0.0
  right_elbow_joint: 1.0
  right_wrist_roll_joint: 0.0
  right_wrist_pitch_joint: 0.0
  right_wrist_yaw_joint: 0.0
