ROBOT_SCENE: "data/robots/g1/g1_29dof_nohand-eef_L-box.xml" # Robot scene, for Sim2Sim

ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time

USE_JOYSTICK: 0 # Simulate Unitree WirelessController using a gamepad (0: disable, 1: enable)

publish_object_names: ["box", "pelvis"]

# we have to put the box parameters in the xml and manually randomize them now
# box_mass: 5.0
# box_size: [0.6, 0.44, 0.65]