ROBOT_SCENE: "data/robots/g1/g1_29dof_nohand.xml" # Robot scene, for Sim2Sim
# ROBOT_SCENE: "data/robots/g1/g1_gmt.xml" # Robot scene, for Sim2Sim

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time

publish_object_names: []